// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppendEntry.proto

package com.raft.message;

public final class AppendEntryProto {
  private AppendEntryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppendEntryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.AppendEntryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
     * </pre>
     */
    boolean hasTerm();
    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
     * </pre>
     */
    int getTerm();

    /**
     * <code>optional string leaderId = 2;</code>
     *
     * <pre>
     *required for client redirection to a leader store IP address in this field
     * </pre>
     */
    boolean hasLeaderId();
    /**
     * <code>optional string leaderId = 2;</code>
     *
     * <pre>
     *required for client redirection to a leader store IP address in this field
     * </pre>
     */
    java.lang.String getLeaderId();
    /**
     * <code>optional string leaderId = 2;</code>
     *
     * <pre>
     *required for client redirection to a leader store IP address in this field
     * </pre>
     */
    com.google.protobuf.ByteString
        getLeaderIdBytes();

    /**
     * <code>optional int32 previousLogIndex = 3;</code>
     *
     * <pre>
     *index of entry immediately preceding the new one
     * </pre>
     */
    boolean hasPreviousLogIndex();
    /**
     * <code>optional int32 previousLogIndex = 3;</code>
     *
     * <pre>
     *index of entry immediately preceding the new one
     * </pre>
     */
    int getPreviousLogIndex();

    /**
     * <code>optional int32 prevLogTerm = 4;</code>
     *
     * <pre>
     * term of previous log entry
     * </pre>
     */
    boolean hasPrevLogTerm();
    /**
     * <code>optional int32 prevLogTerm = 4;</code>
     *
     * <pre>
     * term of previous log entry
     * </pre>
     */
    int getPrevLogTerm();

    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getEntriesList();
    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    int getEntriesCount();
    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    java.lang.String getEntries(int index);
    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    com.google.protobuf.ByteString
        getEntriesBytes(int index);

    /**
     * <code>optional int32 leadersCommit = 6;</code>
     *
     * <pre>
     * leaders commit index
     * </pre>
     */
    boolean hasLeadersCommit();
    /**
     * <code>optional int32 leadersCommit = 6;</code>
     *
     * <pre>
     * leaders commit index
     * </pre>
     */
    int getLeadersCommit();
  }
  /**
   * Protobuf type {@code messages.AppendEntryRequest}
   */
  public static final class AppendEntryRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messages.AppendEntryRequest)
      AppendEntryRequestOrBuilder {
    // Use AppendEntryRequest.newBuilder() to construct.
    private AppendEntryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppendEntryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppendEntryRequest defaultInstance;
    public static AppendEntryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AppendEntryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              leaderId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              previousLogIndex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              prevLogTerm_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                entries_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              entries_.add(bs);
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              leadersCommit_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          entries_ = entries_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.raft.message.AppendEntryProto.AppendEntryRequest.class, com.raft.message.AppendEntryProto.AppendEntryRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AppendEntryRequest> PARSER =
        new com.google.protobuf.AbstractParser<AppendEntryRequest>() {
      public AppendEntryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendEntryRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntryRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
     * </pre>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
     * </pre>
     */
    public int getTerm() {
      return term_;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private java.lang.Object leaderId_;
    /**
     * <code>optional string leaderId = 2;</code>
     *
     * <pre>
     *required for client redirection to a leader store IP address in this field
     * </pre>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string leaderId = 2;</code>
     *
     * <pre>
     *required for client redirection to a leader store IP address in this field
     * </pre>
     */
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          leaderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string leaderId = 2;</code>
     *
     * <pre>
     *required for client redirection to a leader store IP address in this field
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREVIOUSLOGINDEX_FIELD_NUMBER = 3;
    private int previousLogIndex_;
    /**
     * <code>optional int32 previousLogIndex = 3;</code>
     *
     * <pre>
     *index of entry immediately preceding the new one
     * </pre>
     */
    public boolean hasPreviousLogIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 previousLogIndex = 3;</code>
     *
     * <pre>
     *index of entry immediately preceding the new one
     * </pre>
     */
    public int getPreviousLogIndex() {
      return previousLogIndex_;
    }

    public static final int PREVLOGTERM_FIELD_NUMBER = 4;
    private int prevLogTerm_;
    /**
     * <code>optional int32 prevLogTerm = 4;</code>
     *
     * <pre>
     * term of previous log entry
     * </pre>
     */
    public boolean hasPrevLogTerm() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 prevLogTerm = 4;</code>
     *
     * <pre>
     * term of previous log entry
     * </pre>
     */
    public int getPrevLogTerm() {
      return prevLogTerm_;
    }

    public static final int ENTRIES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList entries_;
    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    public java.lang.String getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated string entries = 5;</code>
     *
     * <pre>
     * log entries to store, should be empty for HeartBeats
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEntriesBytes(int index) {
      return entries_.getByteString(index);
    }

    public static final int LEADERSCOMMIT_FIELD_NUMBER = 6;
    private int leadersCommit_;
    /**
     * <code>optional int32 leadersCommit = 6;</code>
     *
     * <pre>
     * leaders commit index
     * </pre>
     */
    public boolean hasLeadersCommit() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 leadersCommit = 6;</code>
     *
     * <pre>
     * leaders commit index
     * </pre>
     */
    public int getLeadersCommit() {
      return leadersCommit_;
    }

    private void initFields() {
      term_ = 0;
      leaderId_ = "";
      previousLogIndex_ = 0;
      prevLogTerm_ = 0;
      entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      leadersCommit_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLeaderIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, previousLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, prevLogTerm_);
      }
      for (int i = 0; i < entries_.size(); i++) {
        output.writeBytes(5, entries_.getByteString(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, leadersCommit_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLeaderIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, previousLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, prevLogTerm_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < entries_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(entries_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getEntriesList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, leadersCommit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.raft.message.AppendEntryProto.AppendEntryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.AppendEntryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.AppendEntryRequest)
        com.raft.message.AppendEntryProto.AppendEntryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.raft.message.AppendEntryProto.AppendEntryRequest.class, com.raft.message.AppendEntryProto.AppendEntryRequest.Builder.class);
      }

      // Construct using com.raft.message.AppendEntryProto.AppendEntryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        previousLogIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        prevLogTerm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        leadersCommit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryRequest_descriptor;
      }

      public com.raft.message.AppendEntryProto.AppendEntryRequest getDefaultInstanceForType() {
        return com.raft.message.AppendEntryProto.AppendEntryRequest.getDefaultInstance();
      }

      public com.raft.message.AppendEntryProto.AppendEntryRequest build() {
        com.raft.message.AppendEntryProto.AppendEntryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.raft.message.AppendEntryProto.AppendEntryRequest buildPartial() {
        com.raft.message.AppendEntryProto.AppendEntryRequest result = new com.raft.message.AppendEntryProto.AppendEntryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.previousLogIndex_ = previousLogIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prevLogTerm_ = prevLogTerm_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          entries_ = entries_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.entries_ = entries_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.leadersCommit_ = leadersCommit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.raft.message.AppendEntryProto.AppendEntryRequest) {
          return mergeFrom((com.raft.message.AppendEntryProto.AppendEntryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.raft.message.AppendEntryProto.AppendEntryRequest other) {
        if (other == com.raft.message.AppendEntryProto.AppendEntryRequest.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasLeaderId()) {
          bitField0_ |= 0x00000002;
          leaderId_ = other.leaderId_;
          onChanged();
        }
        if (other.hasPreviousLogIndex()) {
          setPreviousLogIndex(other.getPreviousLogIndex());
        }
        if (other.hasPrevLogTerm()) {
          setPrevLogTerm(other.getPrevLogTerm());
        }
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
        if (other.hasLeadersCommit()) {
          setLeadersCommit(other.getLeadersCommit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.raft.message.AppendEntryProto.AppendEntryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.raft.message.AppendEntryProto.AppendEntryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
       * </pre>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
       * </pre>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
       * </pre>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       *incremented by candidate before the stat of election; Reject RPC with lower term in candidate state.
       * </pre>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object leaderId_ = "";
      /**
       * <code>optional string leaderId = 2;</code>
       *
       * <pre>
       *required for client redirection to a leader store IP address in this field
       * </pre>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string leaderId = 2;</code>
       *
       * <pre>
       *required for client redirection to a leader store IP address in this field
       * </pre>
       */
      public java.lang.String getLeaderId() {
        java.lang.Object ref = leaderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            leaderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string leaderId = 2;</code>
       *
       * <pre>
       *required for client redirection to a leader store IP address in this field
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLeaderIdBytes() {
        java.lang.Object ref = leaderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string leaderId = 2;</code>
       *
       * <pre>
       *required for client redirection to a leader store IP address in this field
       * </pre>
       */
      public Builder setLeaderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string leaderId = 2;</code>
       *
       * <pre>
       *required for client redirection to a leader store IP address in this field
       * </pre>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderId_ = getDefaultInstance().getLeaderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string leaderId = 2;</code>
       *
       * <pre>
       *required for client redirection to a leader store IP address in this field
       * </pre>
       */
      public Builder setLeaderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        leaderId_ = value;
        onChanged();
        return this;
      }

      private int previousLogIndex_ ;
      /**
       * <code>optional int32 previousLogIndex = 3;</code>
       *
       * <pre>
       *index of entry immediately preceding the new one
       * </pre>
       */
      public boolean hasPreviousLogIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 previousLogIndex = 3;</code>
       *
       * <pre>
       *index of entry immediately preceding the new one
       * </pre>
       */
      public int getPreviousLogIndex() {
        return previousLogIndex_;
      }
      /**
       * <code>optional int32 previousLogIndex = 3;</code>
       *
       * <pre>
       *index of entry immediately preceding the new one
       * </pre>
       */
      public Builder setPreviousLogIndex(int value) {
        bitField0_ |= 0x00000004;
        previousLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 previousLogIndex = 3;</code>
       *
       * <pre>
       *index of entry immediately preceding the new one
       * </pre>
       */
      public Builder clearPreviousLogIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        previousLogIndex_ = 0;
        onChanged();
        return this;
      }

      private int prevLogTerm_ ;
      /**
       * <code>optional int32 prevLogTerm = 4;</code>
       *
       * <pre>
       * term of previous log entry
       * </pre>
       */
      public boolean hasPrevLogTerm() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 prevLogTerm = 4;</code>
       *
       * <pre>
       * term of previous log entry
       * </pre>
       */
      public int getPrevLogTerm() {
        return prevLogTerm_;
      }
      /**
       * <code>optional int32 prevLogTerm = 4;</code>
       *
       * <pre>
       * term of previous log entry
       * </pre>
       */
      public Builder setPrevLogTerm(int value) {
        bitField0_ |= 0x00000008;
        prevLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 prevLogTerm = 4;</code>
       *
       * <pre>
       * term of previous log entry
       * </pre>
       */
      public Builder clearPrevLogTerm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prevLogTerm_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          entries_ = new com.google.protobuf.LazyStringArrayList(entries_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getEntriesList() {
        return entries_.getUnmodifiableView();
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public int getEntriesCount() {
        return entries_.size();
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public java.lang.String getEntries(int index) {
        return entries_.get(index);
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEntriesBytes(int index) {
        return entries_.getByteString(index);
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public Builder setEntries(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public Builder addEntries(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public Builder addAllEntries(
          java.lang.Iterable<java.lang.String> values) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public Builder clearEntries() {
        entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string entries = 5;</code>
       *
       * <pre>
       * log entries to store, should be empty for HeartBeats
       * </pre>
       */
      public Builder addEntriesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
        return this;
      }

      private int leadersCommit_ ;
      /**
       * <code>optional int32 leadersCommit = 6;</code>
       *
       * <pre>
       * leaders commit index
       * </pre>
       */
      public boolean hasLeadersCommit() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 leadersCommit = 6;</code>
       *
       * <pre>
       * leaders commit index
       * </pre>
       */
      public int getLeadersCommit() {
        return leadersCommit_;
      }
      /**
       * <code>optional int32 leadersCommit = 6;</code>
       *
       * <pre>
       * leaders commit index
       * </pre>
       */
      public Builder setLeadersCommit(int value) {
        bitField0_ |= 0x00000020;
        leadersCommit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leadersCommit = 6;</code>
       *
       * <pre>
       * leaders commit index
       * </pre>
       */
      public Builder clearLeadersCommit() {
        bitField0_ = (bitField0_ & ~0x00000020);
        leadersCommit_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.AppendEntryRequest)
    }

    static {
      defaultInstance = new AppendEntryRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.AppendEntryRequest)
  }

  public interface AppendEntryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.AppendEntryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     * for leader to update its term in case term&gt;leadersTerm and become follower
     * </pre>
     */
    boolean hasTerm();
    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     * for leader to update its term in case term&gt;leadersTerm and become follower
     * </pre>
     */
    int getTerm();

    /**
     * <code>optional bool success = 2;</code>
     *
     * <pre>
     *true if follower contained entry matching prevLogIndex and prevLogTerm
     * </pre>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 2;</code>
     *
     * <pre>
     *true if follower contained entry matching prevLogIndex and prevLogTerm
     * </pre>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code messages.AppendEntryResponse}
   */
  public static final class AppendEntryResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messages.AppendEntryResponse)
      AppendEntryResponseOrBuilder {
    // Use AppendEntryResponse.newBuilder() to construct.
    private AppendEntryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppendEntryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppendEntryResponse defaultInstance;
    public static AppendEntryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AppendEntryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.raft.message.AppendEntryProto.AppendEntryResponse.class, com.raft.message.AppendEntryProto.AppendEntryResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AppendEntryResponse> PARSER =
        new com.google.protobuf.AbstractParser<AppendEntryResponse>() {
      public AppendEntryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendEntryResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntryResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     * for leader to update its term in case term&gt;leadersTerm and become follower
     * </pre>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 term = 1;</code>
     *
     * <pre>
     * for leader to update its term in case term&gt;leadersTerm and become follower
     * </pre>
     */
    public int getTerm() {
      return term_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>optional bool success = 2;</code>
     *
     * <pre>
     *true if follower contained entry matching prevLogIndex and prevLogTerm
     * </pre>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool success = 2;</code>
     *
     * <pre>
     *true if follower contained entry matching prevLogIndex and prevLogTerm
     * </pre>
     */
    public boolean getSuccess() {
      return success_;
    }

    private void initFields() {
      term_ = 0;
      success_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, success_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.AppendEntryProto.AppendEntryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.raft.message.AppendEntryProto.AppendEntryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.AppendEntryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.AppendEntryResponse)
        com.raft.message.AppendEntryProto.AppendEntryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.raft.message.AppendEntryProto.AppendEntryResponse.class, com.raft.message.AppendEntryProto.AppendEntryResponse.Builder.class);
      }

      // Construct using com.raft.message.AppendEntryProto.AppendEntryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.raft.message.AppendEntryProto.internal_static_messages_AppendEntryResponse_descriptor;
      }

      public com.raft.message.AppendEntryProto.AppendEntryResponse getDefaultInstanceForType() {
        return com.raft.message.AppendEntryProto.AppendEntryResponse.getDefaultInstance();
      }

      public com.raft.message.AppendEntryProto.AppendEntryResponse build() {
        com.raft.message.AppendEntryProto.AppendEntryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.raft.message.AppendEntryProto.AppendEntryResponse buildPartial() {
        com.raft.message.AppendEntryProto.AppendEntryResponse result = new com.raft.message.AppendEntryProto.AppendEntryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.raft.message.AppendEntryProto.AppendEntryResponse) {
          return mergeFrom((com.raft.message.AppendEntryProto.AppendEntryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.raft.message.AppendEntryProto.AppendEntryResponse other) {
        if (other == com.raft.message.AppendEntryProto.AppendEntryResponse.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.raft.message.AppendEntryProto.AppendEntryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.raft.message.AppendEntryProto.AppendEntryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       * for leader to update its term in case term&gt;leadersTerm and become follower
       * </pre>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       * for leader to update its term in case term&gt;leadersTerm and become follower
       * </pre>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       * for leader to update its term in case term&gt;leadersTerm and become follower
       * </pre>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 term = 1;</code>
       *
       * <pre>
       * for leader to update its term in case term&gt;leadersTerm and become follower
       * </pre>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>optional bool success = 2;</code>
       *
       * <pre>
       *true if follower contained entry matching prevLogIndex and prevLogTerm
       * </pre>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool success = 2;</code>
       *
       * <pre>
       *true if follower contained entry matching prevLogIndex and prevLogTerm
       * </pre>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 2;</code>
       *
       * <pre>
       *true if follower contained entry matching prevLogIndex and prevLogTerm
       * </pre>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 2;</code>
       *
       * <pre>
       *true if follower contained entry matching prevLogIndex and prevLogTerm
       * </pre>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.AppendEntryResponse)
    }

    static {
      defaultInstance = new AppendEntryResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.AppendEntryResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_AppendEntryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_AppendEntryRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_AppendEntryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_AppendEntryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021AppendEntry.proto\022\010messages\"\213\001\n\022Append" +
      "EntryRequest\022\014\n\004term\030\001 \001(\005\022\020\n\010leaderId\030\002" +
      " \001(\t\022\030\n\020previousLogIndex\030\003 \001(\005\022\023\n\013prevLo" +
      "gTerm\030\004 \001(\005\022\017\n\007entries\030\005 \003(\t\022\025\n\rleadersC" +
      "ommit\030\006 \001(\005\"4\n\023AppendEntryResponse\022\014\n\004te" +
      "rm\030\001 \001(\005\022\017\n\007success\030\002 \001(\010B$\n\020com.raft.me" +
      "ssageB\020AppendEntryProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_AppendEntryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_AppendEntryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_AppendEntryRequest_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "PreviousLogIndex", "PrevLogTerm", "Entries", "LeadersCommit", });
    internal_static_messages_AppendEntryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_AppendEntryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_AppendEntryResponse_descriptor,
        new java.lang.String[] { "Term", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
