// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestVote.proto

package com.raft.message;

public final class RequestVoteProto {
  private RequestVoteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VotingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.VotingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 termId = 1;</code>
     */
    boolean hasTermId();
    /**
     * <code>optional int32 termId = 1;</code>
     */
    int getTermId();

    /**
     * <code>optional int32 candidateId = 2;</code>
     *
     * <pre>
     * candidate asking vote; store IP in this field
     * </pre>
     */
    boolean hasCandidateId();
    /**
     * <code>optional int32 candidateId = 2;</code>
     *
     * <pre>
     * candidate asking vote; store IP in this field
     * </pre>
     */
    int getCandidateId();

    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    boolean hasLastLogIndex();
    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    int getLastLogIndex();

    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    boolean hasLastLogTerm();
    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    int getLastLogTerm();
  }
  /**
   * Protobuf type {@code messages.VotingRequest}
   */
  public static final class VotingRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messages.VotingRequest)
      VotingRequestOrBuilder {
    // Use VotingRequest.newBuilder() to construct.
    private VotingRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VotingRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VotingRequest defaultInstance;
    public static VotingRequest getDefaultInstance() {
      return defaultInstance;
    }

    public VotingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VotingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              termId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              candidateId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lastLogIndex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastLogTerm_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.raft.message.RequestVoteProto.internal_static_messages_VotingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.raft.message.RequestVoteProto.internal_static_messages_VotingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.raft.message.RequestVoteProto.VotingRequest.class, com.raft.message.RequestVoteProto.VotingRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<VotingRequest> PARSER =
        new com.google.protobuf.AbstractParser<VotingRequest>() {
      public VotingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VotingRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VotingRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TERMID_FIELD_NUMBER = 1;
    private int termId_;
    /**
     * <code>optional int32 termId = 1;</code>
     */
    public boolean hasTermId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 termId = 1;</code>
     */
    public int getTermId() {
      return termId_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 2;
    private int candidateId_;
    /**
     * <code>optional int32 candidateId = 2;</code>
     *
     * <pre>
     * candidate asking vote; store IP in this field
     * </pre>
     */
    public boolean hasCandidateId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 candidateId = 2;</code>
     *
     * <pre>
     * candidate asking vote; store IP in this field
     * </pre>
     */
    public int getCandidateId() {
      return candidateId_;
    }

    public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
    private int lastLogIndex_;
    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    public boolean hasLastLogIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    public int getLastLogIndex() {
      return lastLogIndex_;
    }

    public static final int LASTLOGTERM_FIELD_NUMBER = 4;
    private int lastLogTerm_;
    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    public boolean hasLastLogTerm() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     *
     * <pre>
     *see section 5.4 RAFT paper
     * </pre>
     */
    public int getLastLogTerm() {
      return lastLogTerm_;
    }

    private void initFields() {
      termId_ = 0;
      candidateId_ = 0;
      lastLogIndex_ = 0;
      lastLogTerm_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, termId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lastLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, lastLogTerm_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, termId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lastLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, lastLogTerm_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.RequestVoteProto.VotingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.raft.message.RequestVoteProto.VotingRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.VotingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.VotingRequest)
        com.raft.message.RequestVoteProto.VotingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.raft.message.RequestVoteProto.internal_static_messages_VotingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.raft.message.RequestVoteProto.internal_static_messages_VotingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.raft.message.RequestVoteProto.VotingRequest.class, com.raft.message.RequestVoteProto.VotingRequest.Builder.class);
      }

      // Construct using com.raft.message.RequestVoteProto.VotingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        termId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        lastLogIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLogTerm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.raft.message.RequestVoteProto.internal_static_messages_VotingRequest_descriptor;
      }

      public com.raft.message.RequestVoteProto.VotingRequest getDefaultInstanceForType() {
        return com.raft.message.RequestVoteProto.VotingRequest.getDefaultInstance();
      }

      public com.raft.message.RequestVoteProto.VotingRequest build() {
        com.raft.message.RequestVoteProto.VotingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.raft.message.RequestVoteProto.VotingRequest buildPartial() {
        com.raft.message.RequestVoteProto.VotingRequest result = new com.raft.message.RequestVoteProto.VotingRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.termId_ = termId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateId_ = candidateId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastLogIndex_ = lastLogIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastLogTerm_ = lastLogTerm_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.raft.message.RequestVoteProto.VotingRequest) {
          return mergeFrom((com.raft.message.RequestVoteProto.VotingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.raft.message.RequestVoteProto.VotingRequest other) {
        if (other == com.raft.message.RequestVoteProto.VotingRequest.getDefaultInstance()) return this;
        if (other.hasTermId()) {
          setTermId(other.getTermId());
        }
        if (other.hasCandidateId()) {
          setCandidateId(other.getCandidateId());
        }
        if (other.hasLastLogIndex()) {
          setLastLogIndex(other.getLastLogIndex());
        }
        if (other.hasLastLogTerm()) {
          setLastLogTerm(other.getLastLogTerm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.raft.message.RequestVoteProto.VotingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.raft.message.RequestVoteProto.VotingRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int termId_ ;
      /**
       * <code>optional int32 termId = 1;</code>
       */
      public boolean hasTermId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 termId = 1;</code>
       */
      public int getTermId() {
        return termId_;
      }
      /**
       * <code>optional int32 termId = 1;</code>
       */
      public Builder setTermId(int value) {
        bitField0_ |= 0x00000001;
        termId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 termId = 1;</code>
       */
      public Builder clearTermId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        termId_ = 0;
        onChanged();
        return this;
      }

      private int candidateId_ ;
      /**
       * <code>optional int32 candidateId = 2;</code>
       *
       * <pre>
       * candidate asking vote; store IP in this field
       * </pre>
       */
      public boolean hasCandidateId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 candidateId = 2;</code>
       *
       * <pre>
       * candidate asking vote; store IP in this field
       * </pre>
       */
      public int getCandidateId() {
        return candidateId_;
      }
      /**
       * <code>optional int32 candidateId = 2;</code>
       *
       * <pre>
       * candidate asking vote; store IP in this field
       * </pre>
       */
      public Builder setCandidateId(int value) {
        bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 candidateId = 2;</code>
       *
       * <pre>
       * candidate asking vote; store IP in this field
       * </pre>
       */
      public Builder clearCandidateId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateId_ = 0;
        onChanged();
        return this;
      }

      private int lastLogIndex_ ;
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public boolean hasLastLogIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public int getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public Builder setLastLogIndex(int value) {
        bitField0_ |= 0x00000004;
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public Builder clearLastLogIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLogIndex_ = 0;
        onChanged();
        return this;
      }

      private int lastLogTerm_ ;
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public boolean hasLastLogTerm() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public int getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public Builder setLastLogTerm(int value) {
        bitField0_ |= 0x00000008;
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       *
       * <pre>
       *see section 5.4 RAFT paper
       * </pre>
       */
      public Builder clearLastLogTerm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastLogTerm_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.VotingRequest)
    }

    static {
      defaultInstance = new VotingRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.VotingRequest)
  }

  public interface VotingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.VotingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool voteGranted = 1;</code>
     *
     * <pre>
     * true means vote granted
     * </pre>
     */
    boolean hasVoteGranted();
    /**
     * <code>optional bool voteGranted = 1;</code>
     *
     * <pre>
     * true means vote granted
     * </pre>
     */
    boolean getVoteGranted();

    /**
     * <code>optional int32 term = 2;</code>
     *
     * <pre>
     * term for which vote is granted
     * </pre>
     */
    boolean hasTerm();
    /**
     * <code>optional int32 term = 2;</code>
     *
     * <pre>
     * term for which vote is granted
     * </pre>
     */
    int getTerm();

    /**
     * <code>optional int32 voterId = 3;</code>
     *
     * <pre>
     *store IP of the node which granted the vote.
     * </pre>
     */
    boolean hasVoterId();
    /**
     * <code>optional int32 voterId = 3;</code>
     *
     * <pre>
     *store IP of the node which granted the vote.
     * </pre>
     */
    int getVoterId();
  }
  /**
   * Protobuf type {@code messages.VotingResponse}
   */
  public static final class VotingResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messages.VotingResponse)
      VotingResponseOrBuilder {
    // Use VotingResponse.newBuilder() to construct.
    private VotingResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VotingResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VotingResponse defaultInstance;
    public static VotingResponse getDefaultInstance() {
      return defaultInstance;
    }

    public VotingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VotingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              voteGranted_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              term_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              voterId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.raft.message.RequestVoteProto.internal_static_messages_VotingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.raft.message.RequestVoteProto.internal_static_messages_VotingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.raft.message.RequestVoteProto.VotingResponse.class, com.raft.message.RequestVoteProto.VotingResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<VotingResponse> PARSER =
        new com.google.protobuf.AbstractParser<VotingResponse>() {
      public VotingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VotingResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VotingResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VOTEGRANTED_FIELD_NUMBER = 1;
    private boolean voteGranted_;
    /**
     * <code>optional bool voteGranted = 1;</code>
     *
     * <pre>
     * true means vote granted
     * </pre>
     */
    public boolean hasVoteGranted() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool voteGranted = 1;</code>
     *
     * <pre>
     * true means vote granted
     * </pre>
     */
    public boolean getVoteGranted() {
      return voteGranted_;
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private int term_;
    /**
     * <code>optional int32 term = 2;</code>
     *
     * <pre>
     * term for which vote is granted
     * </pre>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 term = 2;</code>
     *
     * <pre>
     * term for which vote is granted
     * </pre>
     */
    public int getTerm() {
      return term_;
    }

    public static final int VOTERID_FIELD_NUMBER = 3;
    private int voterId_;
    /**
     * <code>optional int32 voterId = 3;</code>
     *
     * <pre>
     *store IP of the node which granted the vote.
     * </pre>
     */
    public boolean hasVoterId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 voterId = 3;</code>
     *
     * <pre>
     *store IP of the node which granted the vote.
     * </pre>
     */
    public int getVoterId() {
      return voterId_;
    }

    private void initFields() {
      voteGranted_ = false;
      term_ = 0;
      voterId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, voteGranted_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, term_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, voterId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, voteGranted_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, term_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, voterId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.raft.message.RequestVoteProto.VotingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.raft.message.RequestVoteProto.VotingResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.VotingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.VotingResponse)
        com.raft.message.RequestVoteProto.VotingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.raft.message.RequestVoteProto.internal_static_messages_VotingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.raft.message.RequestVoteProto.internal_static_messages_VotingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.raft.message.RequestVoteProto.VotingResponse.class, com.raft.message.RequestVoteProto.VotingResponse.Builder.class);
      }

      // Construct using com.raft.message.RequestVoteProto.VotingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        voteGranted_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        voterId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.raft.message.RequestVoteProto.internal_static_messages_VotingResponse_descriptor;
      }

      public com.raft.message.RequestVoteProto.VotingResponse getDefaultInstanceForType() {
        return com.raft.message.RequestVoteProto.VotingResponse.getDefaultInstance();
      }

      public com.raft.message.RequestVoteProto.VotingResponse build() {
        com.raft.message.RequestVoteProto.VotingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.raft.message.RequestVoteProto.VotingResponse buildPartial() {
        com.raft.message.RequestVoteProto.VotingResponse result = new com.raft.message.RequestVoteProto.VotingResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.voteGranted_ = voteGranted_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.voterId_ = voterId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.raft.message.RequestVoteProto.VotingResponse) {
          return mergeFrom((com.raft.message.RequestVoteProto.VotingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.raft.message.RequestVoteProto.VotingResponse other) {
        if (other == com.raft.message.RequestVoteProto.VotingResponse.getDefaultInstance()) return this;
        if (other.hasVoteGranted()) {
          setVoteGranted(other.getVoteGranted());
        }
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasVoterId()) {
          setVoterId(other.getVoterId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.raft.message.RequestVoteProto.VotingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.raft.message.RequestVoteProto.VotingResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean voteGranted_ ;
      /**
       * <code>optional bool voteGranted = 1;</code>
       *
       * <pre>
       * true means vote granted
       * </pre>
       */
      public boolean hasVoteGranted() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool voteGranted = 1;</code>
       *
       * <pre>
       * true means vote granted
       * </pre>
       */
      public boolean getVoteGranted() {
        return voteGranted_;
      }
      /**
       * <code>optional bool voteGranted = 1;</code>
       *
       * <pre>
       * true means vote granted
       * </pre>
       */
      public Builder setVoteGranted(boolean value) {
        bitField0_ |= 0x00000001;
        voteGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool voteGranted = 1;</code>
       *
       * <pre>
       * true means vote granted
       * </pre>
       */
      public Builder clearVoteGranted() {
        bitField0_ = (bitField0_ & ~0x00000001);
        voteGranted_ = false;
        onChanged();
        return this;
      }

      private int term_ ;
      /**
       * <code>optional int32 term = 2;</code>
       *
       * <pre>
       * term for which vote is granted
       * </pre>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 term = 2;</code>
       *
       * <pre>
       * term for which vote is granted
       * </pre>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>optional int32 term = 2;</code>
       *
       * <pre>
       * term for which vote is granted
       * </pre>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000002;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 term = 2;</code>
       *
       * <pre>
       * term for which vote is granted
       * </pre>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        term_ = 0;
        onChanged();
        return this;
      }

      private int voterId_ ;
      /**
       * <code>optional int32 voterId = 3;</code>
       *
       * <pre>
       *store IP of the node which granted the vote.
       * </pre>
       */
      public boolean hasVoterId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 voterId = 3;</code>
       *
       * <pre>
       *store IP of the node which granted the vote.
       * </pre>
       */
      public int getVoterId() {
        return voterId_;
      }
      /**
       * <code>optional int32 voterId = 3;</code>
       *
       * <pre>
       *store IP of the node which granted the vote.
       * </pre>
       */
      public Builder setVoterId(int value) {
        bitField0_ |= 0x00000004;
        voterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 voterId = 3;</code>
       *
       * <pre>
       *store IP of the node which granted the vote.
       * </pre>
       */
      public Builder clearVoterId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        voterId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.VotingResponse)
    }

    static {
      defaultInstance = new VotingResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.VotingResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_VotingRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_VotingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_VotingResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_VotingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021RequestVote.proto\022\010messages\"_\n\rVotingR" +
      "equest\022\016\n\006termId\030\001 \001(\005\022\023\n\013candidateId\030\002 " +
      "\001(\005\022\024\n\014lastLogIndex\030\003 \001(\005\022\023\n\013lastLogTerm" +
      "\030\004 \001(\005\"D\n\016VotingResponse\022\023\n\013voteGranted\030" +
      "\001 \001(\010\022\014\n\004term\030\002 \001(\005\022\017\n\007voterId\030\003 \001(\005B$\n\020" +
      "com.raft.messageB\020RequestVoteProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_VotingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_VotingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_VotingRequest_descriptor,
        new java.lang.String[] { "TermId", "CandidateId", "LastLogIndex", "LastLogTerm", });
    internal_static_messages_VotingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_VotingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_VotingResponse_descriptor,
        new java.lang.String[] { "VoteGranted", "Term", "VoterId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
